services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: z_nc_duckdb_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - z_nc_duckdb_minio_data:/data
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        echo 'Waiting for MinIO...' &&
        until mc alias set local http://172.23.0.3:9000 minioadmin minioadmin; do
          echo 'MinIO not ready, retrying...';
          sleep 2;
        done &&
        echo 'Connected. Creating buckets...' &&
        mc mb local/bucket --ignore-existing &&
        mc mb local/ducklake --ignore-existing
      "

  postgres:
    image: postgres:16
    container_name: z_nc_duckdb_postgres
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: pgadmin
    ports:
      - "5432:5432"
    volumes:
      - z_nc_duckdb_postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

volumes:
  z_nc_duckdb_minio_data:
  z_nc_duckdb_postgres_data:
